import { HistoricalTimelineEntry } from '../types/timeline';

export const HISTORICAL_TIMELINE: HistoricalTimelineEntry[] = [
  {
    id: '500-bce',
    year: -500,
    displayYear: '500 BCE',
    era: 'Classical Age',
    title: 'Imperial Arteries of the Ancient World',
    summary:
      'Persia, Greek city-states, and early South Asian kingdoms shape connected political and cultural zones across Eurasia.',
    keyEvents: [
      'Achaemenid administrative networks extend from Anatolia to the Indus.',
      'Greek maritime city-states accelerate military and civic experimentation.',
      'Early Buddhist and Confucian thought gain regional traction.',
    ],
    notableRegions: ['Eastern Mediterranean', 'Persian Plateau', 'Indus Basin'],
    dominantPowers: ['Achaemenid Empire', 'Greek Poleis', 'Mahajanapadas'],
    turningPoint: 'Imperial bureaucracy and naval competition begin defining strategic power.',
    culturalShift: 'Philosophical schools and written law become civilizational anchors.',
    tradeContext: 'Royal roads and caravan corridors enable predictable transregional exchange.',
    mapTheme: 'antique',
    mapVariant: 'Classical corridors',
    hotspots: [
      {
        id: 'persepolis',
        label: 'Persepolis',
        region: 'Persian Plateau',
        x: 58,
        y: 42,
        intensity: 'high',
        note: 'Administrative center of imperial logistics.',
      },
      {
        id: 'athens',
        label: 'Athens',
        region: 'Eastern Mediterranean',
        x: 49,
        y: 36,
        intensity: 'medium',
        note: 'Maritime influence and civic experimentation.',
      },
    ],
  },
  {
    id: '0-ce',
    year: 0,
    displayYear: '0',
    era: 'Early Common Era',
    title: 'Imperial Stability and Long-Distance Exchange',
    summary:
      'Roman, Han, and Parthian systems stabilize major corridors, supporting a dense early-global exchange architecture.',
    keyEvents: [
      'Roman frontier governance consolidates Mediterranean commerce.',
      'Han expansion secures Silk Road staging regions.',
      'Intermediary states bridge East-West luxury routes.',
    ],
    notableRegions: ['Mediterranean Basin', 'Central Asia', 'Yellow River Plain'],
    dominantPowers: ['Roman Empire', 'Han Dynasty', 'Parthian Empire'],
    turningPoint: 'Parallel imperial systems reduce transaction risk across continents.',
    culturalShift: 'Religions and legal institutions travel with merchant networks.',
    tradeContext: 'Silk, spices, metals, and ideas move through multi-empire relay routes.',
    mapTheme: 'imperial',
    mapVariant: 'Silk nexus',
    hotspots: [
      {
        id: 'rome',
        label: 'Rome',
        region: 'Mediterranean Basin',
        x: 47,
        y: 33,
        intensity: 'high',
        note: 'Financial and military command center.',
      },
      {
        id: 'changan',
        label: 'Chang’an',
        region: 'Yellow River Plain',
        x: 73,
        y: 34,
        intensity: 'high',
        note: 'Eastern anchor of imperial trade.',
      },
    ],
  },
  {
    id: '476',
    year: 476,
    displayYear: '476',
    era: 'Late Antiquity',
    title: 'Western Fragmentation, Eastern Continuity',
    summary:
      'Western Roman collapse reshapes Europe while Byzantine and Persian institutions preserve strategic state capacity.',
    keyEvents: [
      'Deposition of Romulus Augustulus marks Western imperial rupture.',
      'Byzantine administration preserves Eastern fiscal-military coherence.',
      'Post-Roman successor kingdoms compete for legitimacy and territory.',
    ],
    notableRegions: ['Italian Peninsula', 'Balkans', 'Mesopotamia'],
    dominantPowers: ['Byzantine Empire', 'Sasanian Empire', 'Germanic Kingdoms'],
    turningPoint: 'Institutional continuity shifts east as western power decentralizes.',
    culturalShift: 'Latin-Christian authority and local warlord power interweave.',
    tradeContext: 'Mediterranean routes contract, while eastern inland routes stay resilient.',
    mapTheme: 'antique',
    mapVariant: 'Post-imperial fracture',
    hotspots: [
      {
        id: 'constantinople',
        label: 'Constantinople',
        region: 'Balkans',
        x: 53,
        y: 34,
        intensity: 'high',
        note: 'Critical imperial and maritime chokepoint.',
      },
      {
        id: 'ravenna',
        label: 'Ravenna',
        region: 'Italian Peninsula',
        x: 48,
        y: 33,
        intensity: 'medium',
        note: 'Symbolic seat of collapsing western authority.',
      },
    ],
  },
  {
    id: '800',
    year: 800,
    displayYear: '800',
    era: 'Medieval Consolidation',
    title: 'Competing Sacred and Imperial Orders',
    summary:
      'Carolingian, Abbasid, and Tang systems build durable political spheres linked by diplomacy and trade intelligence.',
    keyEvents: [
      'Coronation of Charlemagne reorganizes western imperial claims.',
      'Abbasid Baghdad anchors science, finance, and translation networks.',
      'Tang-era governance supports East Asian urban and military scale.',
    ],
    notableRegions: ['Western Europe', 'Mesopotamia', 'East Asia'],
    dominantPowers: ['Carolingian Empire', 'Abbasid Caliphate', 'Tang Dynasty'],
    turningPoint: 'Religious legitimacy and state administration become tightly coupled.',
    culturalShift: 'Knowledge transfer accelerates through multilingual scholarly networks.',
    tradeContext: 'Indian Ocean and overland routes converge through Islamic commercial hubs.',
    mapTheme: 'imperial',
    mapVariant: 'Scholarly circuits',
    hotspots: [
      {
        id: 'baghdad',
        label: 'Baghdad',
        region: 'Mesopotamia',
        x: 57,
        y: 38,
        intensity: 'high',
        note: 'Financial and intellectual core of transregional exchange.',
      },
      {
        id: 'aachen',
        label: 'Aachen',
        region: 'Western Europe',
        x: 47,
        y: 30,
        intensity: 'medium',
        note: 'Administrative center of Carolingian authority.',
      },
    ],
  },
  {
    id: '1200',
    year: 1200,
    displayYear: '1200',
    era: 'High Medieval',
    title: 'Continental Rewiring Under Mobile Empires',
    summary:
      'Steppe military revolutions and maritime republic finance restructure risk, logistics, and governance across Eurasia.',
    keyEvents: [
      'Steppe confederations begin rapid campaigns across Eurasia.',
      'Italian maritime republics scale credit-driven shipping systems.',
      'Cross-cultural transmission expands in medicine, math, and navigation.',
    ],
    notableRegions: ['Eurasian Steppe', 'Levant', 'Mediterranean Sea'],
    dominantPowers: ['Mongol Confederations', 'Ayyubid States', 'Venetian Networks'],
    turningPoint: 'Mobility and logistics outpace static frontier defense.',
    culturalShift: 'Cross-border military and technical learning intensifies.',
    tradeContext: 'Credit, convoy systems, and caravan nodes reduce long-haul uncertainty.',
    mapTheme: 'imperial',
    mapVariant: 'Mobility corridors',
    hotspots: [
      {
        id: 'samarkand',
        label: 'Samarkand',
        region: 'Eurasian Steppe',
        x: 63,
        y: 34,
        intensity: 'high',
        note: 'Strategic relay for steppe and settled powers.',
      },
      {
        id: 'venice',
        label: 'Venice',
        region: 'Mediterranean Sea',
        x: 49,
        y: 32,
        intensity: 'medium',
        note: 'Maritime finance and logistics hub.',
      },
    ],
  },
  {
    id: '1492',
    year: 1492,
    displayYear: '1492',
    era: 'Age of Oceanic Expansion',
    title: 'Atlantic Pivot and Imperial Projection',
    summary:
      'Iberian maritime breakthroughs initiate sustained Atlantic empires and shift strategic weight from inland routes to sea lanes.',
    keyEvents: [
      'Columbus voyage opens recurring Atlantic routes for European powers.',
      'Granada’s fall completes Iberian reconquest and resource consolidation.',
      'Early colonial governance models emerge in the Atlantic sphere.',
    ],
    notableRegions: ['Iberia', 'Atlantic Ocean', 'Caribbean'],
    dominantPowers: ['Castile-Aragon', 'Portugal', 'Ottoman Empire'],
    turningPoint: 'Oceanic capability becomes the primary multiplier of imperial reach.',
    culturalShift: 'Cartography, navigation science, and missionary systems globalize.',
    tradeContext: 'Atlantic circuits begin competing with Mediterranean-Indian Ocean flows.',
    mapTheme: 'industrial',
    mapVariant: 'Oceanic projection',
    hotspots: [
      {
        id: 'seville',
        label: 'Seville',
        region: 'Iberia',
        x: 45,
        y: 39,
        intensity: 'high',
        note: 'Financial gateway for Atlantic expeditions.',
      },
      {
        id: 'santo-domingo',
        label: 'Caribbean Outpost',
        region: 'Caribbean',
        x: 28,
        y: 47,
        intensity: 'medium',
        note: 'Early colonial governance node.',
      },
    ],
  },
  {
    id: '1776',
    year: 1776,
    displayYear: '1776',
    era: 'Revolutionary Era',
    title: 'Sovereignty Reframed by Atlantic Revolutions',
    summary:
      'Revolutionary political theory, fiscal warfare, and global maritime conflict redraw legitimacy and alliance systems.',
    keyEvents: [
      'American Declaration reframes sovereignty and constitutional governance.',
      'European great-power rivalry spills across Atlantic theaters.',
      'State borrowing and taxation capacity become decisive war factors.',
    ],
    notableRegions: ['North Atlantic', 'North America', 'Western Europe'],
    dominantPowers: ['British Empire', 'Revolutionary America', 'French Kingdom'],
    turningPoint: 'Legitimacy shifts from dynastic entitlement toward popular mandate.',
    culturalShift: 'Print culture scales political mobilization and ideological diffusion.',
    tradeContext: 'Convoys, naval blockades, and colonial commodities shape strategic finance.',
    mapTheme: 'industrial',
    mapVariant: 'Revolutionary arcs',
    hotspots: [
      {
        id: 'philadelphia',
        label: 'Philadelphia',
        region: 'North America',
        x: 26,
        y: 34,
        intensity: 'high',
        note: 'Constitutional and diplomatic coordination center.',
      },
      {
        id: 'london',
        label: 'London',
        region: 'North Atlantic',
        x: 44,
        y: 28,
        intensity: 'high',
        note: 'Imperial finance and naval command node.',
      },
    ],
  },
  {
    id: '1914',
    year: 1914,
    displayYear: '1914',
    era: 'Industrial Total War',
    title: 'Alliance Chains Trigger Global Conflict',
    summary:
      'Industrial mobilization, alliance commitments, and imperial competition ignite a system-wide war with unprecedented scale.',
    keyEvents: [
      'Assassination in Sarajevo activates rigid alliance obligations.',
      'Rapid rail mobilization converts regional crisis into continental war.',
      'Colonial resources and maritime control globalize the conflict.',
    ],
    notableRegions: ['Europe', 'Middle East', 'North Atlantic'],
    dominantPowers: ['British Empire', 'German Empire', 'Russian Empire'],
    turningPoint: 'Industrial capacity overtakes maneuver as the core determinant of endurance.',
    culturalShift: 'Mass media and mechanized warfare alter public perception of conflict.',
    tradeContext: 'Blockades and wartime logistics weaponize global supply routes.',
    mapTheme: 'industrial',
    mapVariant: 'Trench frontiers',
    hotspots: [
      {
        id: 'western-front',
        label: 'Western Front',
        region: 'Europe',
        x: 47,
        y: 30,
        intensity: 'high',
        note: 'Protracted attrition line with industrial firepower.',
      },
      {
        id: 'sarajevo',
        label: 'Sarajevo',
        region: 'Europe',
        x: 50,
        y: 34,
        intensity: 'medium',
        note: 'Crisis trigger point for alliance cascade.',
      },
    ],
  },
  {
    id: '1945',
    year: 1945,
    displayYear: '1945',
    era: 'Postwar Reordering',
    title: 'Bipolar Architecture and Institutional Order',
    summary:
      'World War II ends with a U.S.-Soviet strategic divide and institution-building designed to manage global instability.',
    keyEvents: [
      'UN framework established for postwar security coordination.',
      'Nuclear weapons redefine deterrence and escalation models.',
      'Decolonization pressures begin fracturing legacy empires.',
    ],
    notableRegions: ['North America', 'Eastern Europe', 'Pacific'],
    dominantPowers: ['United States', 'Soviet Union', 'United Kingdom'],
    turningPoint: 'Deterrence and bloc alignment replace multipolar imperial rivalry.',
    culturalShift: 'Human rights discourse and reconstruction narratives gain global traction.',
    tradeContext: 'Bretton Woods mechanisms structure postwar financial stability.',
    mapTheme: 'modern',
    mapVariant: 'Postwar blocs',
    hotspots: [
      {
        id: 'washington',
        label: 'Washington',
        region: 'North America',
        x: 24,
        y: 34,
        intensity: 'high',
        note: 'Anchor of emerging western security-finance architecture.',
      },
      {
        id: 'moscow',
        label: 'Moscow',
        region: 'Eastern Europe',
        x: 57,
        y: 26,
        intensity: 'high',
        note: 'Strategic center of Soviet bloc planning.',
      },
    ],
  },
  {
    id: '1991',
    year: 1991,
    displayYear: '1991',
    era: 'Post-Cold War Transition',
    title: 'Unipolar Moment and Network Globalization',
    summary:
      'Soviet dissolution accelerates market integration, digital networking, and U.S.-led security structures.',
    keyEvents: [
      'Soviet Union dissolves, ending bipolar geopolitical architecture.',
      'Coalition warfare in the Gulf demonstrates precision military doctrine.',
      'Global trade liberalization accelerates capital and manufacturing flows.',
    ],
    notableRegions: ['Eastern Europe', 'Persian Gulf', 'Pacific Rim'],
    dominantPowers: ['United States', 'European Community', 'Rising East Asia'],
    turningPoint: 'Geopolitical competition shifts toward economic and technological leverage.',
    culturalShift: 'Satellite media and early internet tools alter information velocity.',
    tradeContext: 'Container logistics and trade agreements compress distance in supply chains.',
    mapTheme: 'modern',
    mapVariant: 'Globalization grid',
    hotspots: [
      {
        id: 'brussels',
        label: 'Brussels',
        region: 'Eastern Europe',
        x: 46,
        y: 29,
        intensity: 'medium',
        note: 'Regional integration and regulatory coordination hub.',
      },
      {
        id: 'riyadh',
        label: 'Riyadh',
        region: 'Persian Gulf',
        x: 56,
        y: 42,
        intensity: 'medium',
        note: 'Energy and coalition logistics center.',
      },
    ],
  },
  {
    id: '2001',
    year: 2001,
    displayYear: '2001',
    era: 'Security Realignment',
    title: 'Asymmetric Threats and Persistent Surveillance',
    summary:
      'Networked terrorism forces doctrine shifts toward intelligence fusion, expeditionary operations, and domestic security expansion.',
    keyEvents: [
      'September attacks trigger global counterterror coalitions.',
      'Rapid homeland security restructuring expands surveillance programs.',
      'Intervention campaigns redefine alliance burden-sharing.',
    ],
    notableRegions: ['North America', 'Afghanistan', 'Middle East'],
    dominantPowers: ['United States', 'NATO Coalition', 'Regional Security States'],
    turningPoint: 'Persistent non-state threats become central to grand strategy.',
    culturalShift: 'Security narratives reshape legal, civic, and digital spaces.',
    tradeContext: 'Critical infrastructure protection becomes core to economic continuity.',
    mapTheme: 'modern',
    mapVariant: 'Counterterror theater',
    hotspots: [
      {
        id: 'new-york',
        label: 'New York',
        region: 'North America',
        x: 27,
        y: 33,
        intensity: 'high',
        note: 'Catalyst event for strategic doctrine reset.',
      },
      {
        id: 'kabul',
        label: 'Kabul',
        region: 'Afghanistan',
        x: 62,
        y: 37,
        intensity: 'medium',
        note: 'Primary theater of coalition operations.',
      },
    ],
  },
  {
    id: '2025',
    year: 2025,
    displayYear: '2025',
    era: 'Multipolar Competition',
    title: 'AI-Era Fragmentation and Chokepoint Strategy',
    summary:
      'Strategic competition centers on compute, chips, maritime chokepoints, and narrative control across tightly linked crises.',
    keyEvents: [
      'AI infrastructure races drive state-private strategic partnerships.',
      'Maritime disruption and sanctions reshape routing decisions in real time.',
      'Regional conflicts and cyber operations fuse kinetic and digital theaters.',
    ],
    notableRegions: ['Indo-Pacific', 'Eastern Europe', 'Red Sea'],
    dominantPowers: ['United States', 'China', 'Networked Middle Powers'],
    turningPoint: 'Technology stack control becomes as decisive as territorial control.',
    culturalShift: 'Synthetic media and platform ecosystems redefine trust at scale.',
    tradeContext: 'Resilient supply chains prioritize redundancy over pure efficiency.',
    mapTheme: 'modern',
    mapVariant: 'AI-geopolitics mesh',
    hotspots: [
      {
        id: 'taiwan-strait',
        label: 'Taiwan Strait',
        region: 'Indo-Pacific',
        x: 76,
        y: 40,
        intensity: 'high',
        note: 'Semiconductor and maritime deterrence flashpoint.',
      },
      {
        id: 'red-sea',
        label: 'Red Sea Corridor',
        region: 'Red Sea',
        x: 55,
        y: 43,
        intensity: 'high',
        note: 'Shipping security pressure on global commerce.',
      },
    ],
  },
];

export const DEFAULT_TIMELINE_YEAR_ID = HISTORICAL_TIMELINE[HISTORICAL_TIMELINE.length - 1].id;
